INFO:__main__:[frag] return self.__get_result()
INFO:__main__:[frag] ^^^^^^^^^^^^^^^^^^^
INFO:__main__:[frag] File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
INFO:__main__:[frag] raise self._exception
INFO:__main__:[frag] File "/home/container/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__
INFO:__main__:[frag] result = fn(*args, **kwargs)
INFO:__main__:[frag] ^^^^^^^^^^^^^^^^^^^
INFO:__main__:[frag] File "/home/container/.local/lib/python3.11/site-packages/ratelimit/decorators.py", line 80, in wrapper
INFO:__main__:[frag] return func(*args, **kargs)
INFO:__main__:[frag] ^^^^^^^^^^^^^^^^^^^^
INFO:__main__:[frag] File "/home/container/lokbot/client.py", line 155, in post
INFO:__main__:[frag] raise NotOnlineException()
INFO:__main__:[frag] lokbot.exceptions.NotOnlineException
INFO:__main__:[frag] During handling of the above exception, another exception occurred:
INFO:__main__:[frag] Traceback (most recent call last):
INFO:__main__:[frag] File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
INFO:__main__:[frag] self.run()
INFO:__main__:[frag] File "/usr/local/lib/python3.11/threading.py", line 982, in run
INFO:__main__:[frag] self._target(*self._args, **self._kwargs)
INFO:__main__:[frag] File "/home/container/.local/lib/python3.11/site-packages/socketio/client.py", line 621, in _handle_eio_message
INFO:__main__:[frag] self._handle_event(pkt.namespace, pkt.id, pkt.data)
INFO:__main__:[frag] File "/home/container/.local/lib/python3.11/site-packages/socketio/client.py", line 505, in _handle_event
INFO:__main__:[frag] r = self._trigger_event(data[0], namespace, *data[1:])
INFO:__main__:[frag] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INFO:__main__:[frag] File "/home/container/.local/lib/python3.11/site-packages/socketio/client.py", line 555, in _trigger_event
INFO:__main__:[frag] return self.handlers[namespace][event](*args)
INFO:__main__:[frag] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INFO:__main__:[frag] File "/home/container/lokbot/farmer.py", line 3185, in on_field_objects
INFO:__main__:[frag] self._on_field_objects_gather(each_obj)
INFO:__main__:[frag] File "/home/container/lokbot/farmer.py", line 1455, in _on_field_objects_gather
INFO:__main__:[frag] raise tenacity.TryAgain()
INFO:__main__:[frag] tenacity.TryAgain